### ISSUE TITLE
启动docker失败，给小弟点指点

### ISSUE THREAD

**Issue by XShandow** [fuck-xuexiqiangguo/docker#21]
PS E:\Xuexi> docker logs -f xuexi
failed: Connection refused.
failed: Cannot assign requested address.
....
....
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (/app/resources/electron.asar/browser/init.js:121:9)
    at Object.<anonymous> (/app/resources/electron.asar/browser/init.js:191:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)

**Comment by XShandow** [comment]
手机号和密码已经增加到脚本

**Comment by XShandow** [comment]
![image](https://user-images.githubusercontent.com/15667872/109094664-519b7480-7755-11eb-9b5f-f5a734348922.png)

**Comment by XShandow** [comment]
![image](https://user-images.githubusercontent.com/15667872/109094720-6841cb80-7755-11eb-8702-70478f82f3b6.png)
